//
//  ProphetPricesPresenter.swift
//  AnimalCrossing
//
//  Created by Anastasiya Kudasheva on 08.07.2021.
//  Copyright (c) 2021 All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IProphetPricesPresenter {
    var viewController: IProphetPricesViewController? { get set }
    var viewModel: ProphetPrices.Turnip.ViewModel? { get set }
    func presentSomething(response: ProphetPrices.Turnip.Response?)
}

class ProphetPricesPresenter: IProphetPricesPresenter {
    weak var viewController: IProphetPricesViewController?
    var viewModel: ProphetPrices.Turnip.ViewModel?
    
    func presentSomething(response: ProphetPrices.Turnip.Response?) {
        let dates = ProphetPrices.Turnip.ViewModel.Dates()
        
        guard let response = response,
              response.minWeekValue != 0
        else {
			self.viewController?.displayEmptyScreen()
            return
        }
        let prices = ProphetPrices.Turnip.ViewModel.Prices(from: response)
        let minMaxPice = ProphetPrices.Turnip.ViewModel.PriceForGraph(prices: prices)
		self.viewController?.displayDateViews(dates: dates)
		self.viewController?.displayPrices(prices: prices)
		self.viewController?.displayGraph(with: minMaxPice)
		self.viewController?.displayAll()
    }
}
